services:
  # Laravel App Container
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - redis
    networks:
      - laravel
    environment:
      APP_ENV: local
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: snusempire
      DB_USERNAME: root
      DB_PASSWORD: Passw0rd
      CACHE_DRIVER: database
      SESSION_DRIVER: database
      QUEUE_CONNECTION: database
      REDIS_CLIENT: phpredis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: null

  # MySQL Database Container
  db:
    image: mysql:8
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Passw0rd
      MYSQL_DATABASE: snusempire
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"  # Keep the default MySQL port
    networks:
      - laravel

  # Redis Container
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  mysql_data:
